spring:
  application:
    name:FramkyService

server:
  port: 9090

DolarOff: 6.9

greeting:
  messages:
    en: "Ask yourself if what you are doing today is getting you closer to the place you want to be tomorrow"
    es: "Preguntate si lo que estas haciendo hoy te acerca al lugar en el que quieres estar manana"